### ISSUE TITLE
This package don't play well with NSSM

### ISSUE THREAD

**Issue by andreynering** [kardianos/minwinsvc#1]
See https://github.com/gogits/gogs/issues/2189

When this package is included, [NSSM](https://nssm.cc/) stops working. It would be good if we could prevent minwinsvc from being executed.

**Comment by kardianos** [comment]
@andreynering The fix would be to alter https://godoc.org/golang.org/x/sys/windows/svc#IsAnInteractiveSession
to detect if there is a parent process being run as a service. Not entirely sure if that will work though. Feel free to try though.

The problem you describe is minwinsvc detects it is being run under a windows service and tries to register the needed callbacks, but NSSM already has. Chaos ensues.

Otherwise because minwinsvc manages the windows service natively, you don't need to use nssm anymore.

**Comment by andreynering** [comment]
Thank you for the information. I may take a look.

> Otherwise because minwinsvc manages the windows service natively, you don't need to use nssm anymore.

I agree. I don't know how many people uses NSSM vs. Native with Gogs, but everybody that uses NSSM would have to migrate to be able to upgrade. By now, there are duplicated builds: https://github.com/gogits/gogs/releases/tag/v0.8.10
